[staging]

[global]
template_dir = "templates"

[production]
workers = 1
keep_alive = 5
log = "critical"
base_url = "https://guapa.herokuapp.com/"
limits = { forms = 8192 }

[global.limits]
json = 5242880
